/*
SQLyog Ultimate v11.42 (64 bit)
MySQL - 10.1.38-MariaDB : Database - crud
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`crud` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `crud`;

/*Table structure for table `user` */

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `USERID` double NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(25) DEFAULT NULL,
  `PASSWORD` varchar(36) DEFAULT NULL,
  `OLDPASSWORD` varchar(25) DEFAULT NULL,
  `FULLNAME` varchar(50) DEFAULT NULL,
  `USERMAIL` text,
  `USERPHONE` varchar(15) DEFAULT NULL,
  `USERIMAGE` varchar(35) DEFAULT 'profile.jpg',
  `USERLANGUAGE` double DEFAULT '1',
  `USERISACTIVE` double DEFAULT '0',
  `ADMIN` double DEFAULT '0',
  `USERSTATUS` double DEFAULT '0',
  `MENUPROJECT` double DEFAULT '0',
  `MENUBUGS` double DEFAULT '0',
  `MENUNOTE` double DEFAULT '0',
  `MENUCLIENT` double DEFAULT '0',
  `MENUEXPENSES` double DEFAULT '0',
  `MENUSUPPORT` double DEFAULT '0',
  `MENUPRODUCT` double DEFAULT '0',
  `MENUBID` double DEFAULT '0',
  `MENUREPORTS` double DEFAULT '0',
  `MENUNOTIFI` double DEFAULT '0',
  `MENUSETTING` double DEFAULT '0',
  `MENUTASK` double DEFAULT '0',
  `PROJECTADD` double DEFAULT '0',
  `PROJECTEDIT` double DEFAULT '0',
  `PROJECTDELETE` double DEFAULT '0',
  `PROJECTFULLVIEW` double DEFAULT '0',
  `PROJECTTASKADD` double DEFAULT '0',
  `PROJECTTASKDELETE` double DEFAULT '0',
  `PROJECTTASKEDIT` double DEFAULT '0',
  `CLIENTADD` double DEFAULT '0',
  `CLIENTEDIT` double DEFAULT '0',
  `CLIENTDELETE` double DEFAULT '0',
  `CLIENTVIEW` double DEFAULT '0',
  `EXPENSESFULLVIEW` double DEFAULT '0',
  `REVENUESFULLVIEW` double DEFAULT '0',
  `BUGADD` double DEFAULT '0',
  `BUGEDIT` double DEFAULT '0',
  `BUGDELETE` double DEFAULT '0',
  `NOTEADD` double DEFAULT '0',
  `NOTEDELETE` double DEFAULT '0',
  `NOTEEDIT` double DEFAULT '0',
  `SUPPORTDETAIL` double DEFAULT '0',
  `SUPPORTDELETE` double DEFAULT '0',
  `FILEADD` double DEFAULT '0',
  PRIMARY KEY (`USERID`),
  KEY `USERID` (`USERID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

/*Data for the table `user` */

insert  into `user`(`USERID`,`USERNAME`,`PASSWORD`,`OLDPASSWORD`,`FULLNAME`,`USERMAIL`,`USERPHONE`,`USERIMAGE`,`USERLANGUAGE`,`USERISACTIVE`,`ADMIN`,`USERSTATUS`,`MENUPROJECT`,`MENUBUGS`,`MENUNOTE`,`MENUCLIENT`,`MENUEXPENSES`,`MENUSUPPORT`,`MENUPRODUCT`,`MENUBID`,`MENUREPORTS`,`MENUNOTIFI`,`MENUSETTING`,`MENUTASK`,`PROJECTADD`,`PROJECTEDIT`,`PROJECTDELETE`,`PROJECTFULLVIEW`,`PROJECTTASKADD`,`PROJECTTASKDELETE`,`PROJECTTASKEDIT`,`CLIENTADD`,`CLIENTEDIT`,`CLIENTDELETE`,`CLIENTVIEW`,`EXPENSESFULLVIEW`,`REVENUESFULLVIEW`,`BUGADD`,`BUGEDIT`,`BUGDELETE`,`NOTEADD`,`NOTEDELETE`,`NOTEEDIT`,`SUPPORTDETAIL`,`SUPPORTDELETE`,`FILEADD`) values (1,'denizartunaydin','c4ca4238a0b923820dcc509a6f75849b','1','Deniz Artun Aydın','info@denizartunaydin.com','000000000000','denizartunaydin.png',2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,0),(3,'admin','c4ca4238a0b923820dcc509a6f75849b','1','Admin','admin@admin.com','5555555555555','profile.jpg',1,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);

/*Table structure for table `user_status` */

DROP TABLE IF EXISTS `user_status`;

CREATE TABLE `user_status` (
  `USERSTATUSID` double NOT NULL AUTO_INCREMENT,
  `USERSTATUSNAME` varchar(25) DEFAULT NULL,
  `USERSTATUSISACTIVE` double DEFAULT '0',
  PRIMARY KEY (`USERSTATUSID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

/*Data for the table `user_status` */

insert  into `user_status`(`USERSTATUSID`,`USERSTATUSNAME`,`USERSTATUSISACTIVE`) values (1,'Project Manager',1),(2,'Frontend Developer',1),(3,'Backend Developer',1),(4,'Android Developer',1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
